development:
  adapter: postgresql
  encoding: unicode
  database: notes_development
  pool: 5
  username: guajardo
  password: sdf542gg

test:
  adapter: postgresql
  encoding: unicode
  database: notes_test
  pool: 5
  username: guajardo
  password: sdf542gg